const pathData = `example/adaptiveLayout&flex.html
example/adaptiveLayout&float.html
example/adaptiveLayout&inline-block.html
example/borderTriangle.html
example/calculate&flex&simple.html
example/calculate&flex.html
example/center.html
example/debounce-throttle.html
example/float.html
example/forceCache.html
example/formData.html
example/formSelect.html
example/hidden.html
example/loading.html
example/menu&flex.html
example/menu&float.html
example/onClick&click.html
example/over&enter.html
example/page&offset&client.html
example/ready&onload.html
example/swapDomNode.html
example/table&calendar.html
example/table&sortData.html
example/table.html
example/urlReqTest.html
index.html
`;