const pathData = `const pathData = `example/adaptiveLayout&flex.html
example/adaptiveLayout&float.html
example/adaptiveLayout&inline-block.html
example/appearanceModal.html
example/background.html
example/bind-on.html
example/borderTriangle.html
example/calculate&flex&simple.html
example/calculate&flex.html
example/center.html
example/client&scroll&offset.html
example/datalist&raw.html
example/debounce-throttle.html
example/dialog.html
example/divResize.html
example/DOMContentLoaded.html
example/drag&drag.html
example/drag&simple.html
example/eluosi&game.html
example/fileUpload.html
example/float&margin.html
example/float.html
example/followingBox.html
example/forceCache.html
example/formData.html
example/formSelect.html
example/getElement&querySelector.html
example/grail.html
example/hidden.html
example/input&sort.html
example/lazyLoadImg.html
example/lineHeight.html
example/loading.html
example/menu&flex.html
example/menu&float.html
example/menu.html
example/onClick&click.html
example/over&enter.html
example/page&offset&client.html
example/phone&rem.html
example/phone&scale.html
example/phone&viewport.html
example/progress&animationiteration.html
example/progress.html
example/ready&onload.html
example/requestAnimationFrame.html
example/scroll-client-offset&Top.html
example/simple.html
example/swapDomNode.html
example/table&calendar.html
example/table&filldata.html
example/table&sortData.html
example/table.html
example/transition&autoHeight.html
example/traverse.html
example/urlReqTest.html
example/wing&grid.html
example/wing.html
index.html
node_modules/jquery/src/var/rnothtmlwhite.js
`;`;